name: CI/CD Pipeline Docker & Render

on:
  push:
    branches: [ "main" ] # Cambia a "master" si tu rama principal se llama así

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Construir y subir imagen a Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/DOCKER_HUB_JASMIN:latest

  deploy-to-production:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"